### ISSUE TITLE
Errors on upload

### ISSUE THREAD

**Issue by kmpoppe** [kmpoppe/noteSolver#1]
Reported by https://www.openstreetmap.org/user/Nordpfeil:

```
{{{
URL:https://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2020-04-06 02:17:07 +0200 (Mon, 06 Apr 2020)
Build-Date:2020-04-06 00:18:43
Revision:16239
Relative:URL: ^/trunk

Identification: JOSM/1.5 (16239 de) Windows 10 64-Bit
OS Build number: Windows 10 Enterprise 1909 (18363)
Memory Usage: 989 MB / 989 MB (326 MB allocated, but free)
Java version: 1.8.0_251-b08, Oracle Corporation, Java HotSpot(TM) Client VM
Screen: \Display0 2560x1080
Maximum Screen Size: 2560x1080
Dataset consistency test: No problems found

Plugins:
+ HouseNumberTaggingTool (35248)
+ ImproveWay (29)
+ OpeningHoursEditor (35414)
+ RoadSigns (35424)
+ Tracer2 (35405)
+ continuosDownload (91)
+ contourmerge (v0.1.6)
+ imagery_offset_db (35405)
+ indoor_sweepline (35248)
+ mapathoner (1.0.6)
+ measurement (35405)
+ merge-overlap (35248)
+ notesolver (UNKNOWN)
+ tageditor (35258)
+ terracer (35327)
+ turnlanes-tagging (283)
+ turnrestrictions (35405)
+ undelete (35405)
+ utilsplugin2 (35440)
+ wikipedia (1.1.3)

Tagging presets:
+ https://josm.openstreetmap.de/josmfile?page=Presets/Animal_facilities&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/Playground_Equipment&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/pedestrian_crossings_in_DE&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/Healthcare&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/Crafts&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/Industrial&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/Maxspeed-zones&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/NewParkingFeatures&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/NewTags&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/Simple_Indoor_Tagging&zip=1
+ https://raw.githubusercontent.com/yopaseopor/traffic_signs_preset_JOSM/master/DE.zip
+ https://josm.openstreetmap.de/josmfile?page=Presets/public_bookcase&zip=1

Map paint styles:
- https://raw.githubusercontent.com/yopaseopor/indoormap/master/indoormap-style.mapcss
- https://josm.openstreetmap.de/josmfile?page=Styles/Coloured_Streets&zip=1
- https://www.dropbox.com/s/qo3ai47fpv241jf/Styles_Fixme_and_Notes.zip?raw=1
- https://josm.openstreetmap.de/josmfile?page=Styles/MaxspeedIcons&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Maxspeed&zip=1
- https://github.com/GlassOceanos/indoor-JOSM-style/archive/master.zip
- https://josm.openstreetmap.de/josmfile?page=Styles/ParkingLanes&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/PublicTransport&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Schools&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/PTStops&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Noname&zip=1
Last errors/warnings:
- E: Fehlerhafte Anfrage - <html>Der OSM-Server »api.openstreetmap.org« meldete eine fehlerhafte Anfrage.<br><br>Das angeforderte Gebiet ist zu groß oder enthält zu viele Daten.<br>Versuchen Sie, ein kleineres Gebiet herunterzuladen oder nutzen Sie einen Datenbankexport.</html>
- E: org.openstreetmap.josm.io.OsmApiException: ResponseCode=400, Error Header=<You requested too many nodes (limit is 50000). Either request a smaller area, or use planet.osm>
- E: Fehlerhafte Anfrage - <html>Der OSM-Server »api.openstreetmap.org« meldete eine fehlerhafte Anfrage.<br><br>Das angeforderte Gebiet ist zu groß oder enthält zu viele Daten.<br>Versuchen Sie, ein kleineres Gebiet herunterzuladen oder nutzen Sie einen Datenbankexport.</html>
- E: org.openstreetmap.josm.io.OsmApiException: ResponseCode=400, Error Header=<You requested too many nodes (limit is 50000). Either request a smaller area, or use planet.osm>
- E: Fehlerhafte Anfrage - <html>Der OSM-Server »api.openstreetmap.org« meldete eine fehlerhafte Anfrage.<br><br>Das angeforderte Gebiet ist zu groß oder enthält zu viele Daten.<br>Versuchen Sie, ein kleineres Gebiet herunterzuladen oder nutzen Sie einen Datenbankexport.</html>
- E: org.openstreetmap.josm.io.OsmApiException: ResponseCode=400, Error Header=<You requested too many nodes (limit is 50000). Either request a smaller area, or use planet.osm>
- E: Fehlerhafte Anfrage - <html>Der OSM-Server »api.openstreetmap.org« meldete eine fehlerhafte Anfrage.<br><br>Das angeforderte Gebiet ist zu groß oder enthält zu viele Daten.<br>Versuchen Sie, ein kleineres Gebiet herunterzuladen oder nutzen Sie einen Datenbankexport.</html>
- W: Trying to unset readOnly flag on a non-readOnly dataset 
- E: Handled by bug report queue: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
- W: Achtung - <html>JOSM konnte keine Informationen über die folgenden Erweiterungen finden:<ul><li>ImproveWay</li><li>notesolver</li><li>imagery_offset_db</li><li>HouseNumberTaggingTool</li><li>tageditor</li><li>RoadSigns</li><li>measurement</li><li>continuosDownload</li><li>turnlanes-tagging</li><li>utilsplugin2</li><li>mapathoner</li><li>indoor_sweepline</li><li>OpeningHoursEditor</li><li>undelete</li><li>terracer</li><li>turnrestrictions</li><li>wikipedia</li><li>Tracer2</li><li>contourmerge</li><li>merge-overlap</li></ul>Diese Erweiterungen werden nicht geladen.</html>


=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException
=== STACK TRACE ===
Thread: AWT-EventQueue-0 (15) of main
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
  at org.openstreetmap.josm.plugins.notesolver.NoteSolverPlugin.getUrl(NoteSolverPlugin.java:334)
  at org.openstreetmap.josm.plugins.notesolver.NoteSolverPlugin.access$300(NoteSolverPlugin.java:28)
  at org.openstreetmap.josm.plugins.notesolver.NoteSolverPlugin$6.otherDatasetChange(NoteSolverPlugin.java:188)
  at org.openstreetmap.josm.data.osm.event.ChangesetIdChangedEvent.fire(ChangesetIdChangedEvent.java:34)
  at org.openstreetmap.josm.data.osm.DataSet.fireEventToListeners(DataSet.java:1010)
  at org.openstreetmap.josm.data.osm.DataSet.endUpdate(DataSet.java:941)
  at org.openstreetmap.josm.io.DiffResultProcessor.postProcess(DiffResultProcessor.java:159)
  at org.openstreetmap.josm.io.OsmApi.uploadDiff(OsmApi.java:573)
  at org.openstreetmap.josm.io.OsmServerWriter.uploadChangesAsDiffUpload(OsmServerWriter.java:135)
  at org.openstreetmap.josm.io.OsmServerWriter.uploadOsm(OsmServerWriter.java:211)
  at org.openstreetmap.josm.gui.io.UploadPrimitivesTask.realRun(UploadPrimitivesTask.java:261)
  at org.openstreetmap.josm.gui.io.AsynchronousUploadPrimitivesTask.realRun(AsynchronousUploadPrimitivesTask.java:129)
  at org.openstreetmap.josm.gui.PleaseWaitRunnable.doRealRun(PleaseWaitRunnable.java:94)
  at org.openstreetmap.josm.gui.PleaseWaitRunnable.run(PleaseWaitRunnable.java:142)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  at java.lang.Thread.run(Unknown Source)
}}}

{{{
URL:https://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2020-04-06 02:17:07 +0200 (Mon, 06 Apr 2020)
Build-Date:2020-04-06 00:18:43
Revision:16239
Relative:URL: ^/trunk

Identification: JOSM/1.5 (16239 de) Windows 10 64-Bit
OS Build number: Windows 10 Enterprise 1909 (18363)
Memory Usage: 989 MB / 989 MB (147 MB allocated, but free)
Java version: 1.8.0_251-b08, Oracle Corporation, Java HotSpot(TM) Client VM
Screen: \Display0 2560x1080
Maximum Screen Size: 2560x1080
Dataset consistency test: No problems found

Plugins:
+ HouseNumberTaggingTool (35248)
+ ImproveWay (29)
+ OpeningHoursEditor (35414)
+ RoadSigns (35424)
+ Tracer2 (35405)
+ continuosDownload (91)
+ contourmerge (v0.1.6)
+ imagery_offset_db (35405)
+ indoor_sweepline (35248)
+ mapathoner (1.0.6)
+ measurement (35405)
+ merge-overlap (35248)
+ notesolver (UNKNOWN)
+ tageditor (35258)
+ terracer (35327)
+ turnlanes-tagging (283)
+ turnrestrictions (35405)
+ undelete (35405)
+ utilsplugin2 (35440)
+ wikipedia (1.1.3)

Tagging presets:
+ https://josm.openstreetmap.de/josmfile?page=Presets/Animal_facilities&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/Playground_Equipment&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/pedestrian_crossings_in_DE&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/Healthcare&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/Crafts&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/Industrial&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/Maxspeed-zones&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/NewParkingFeatures&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/NewTags&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/Simple_Indoor_Tagging&zip=1
+ https://raw.githubusercontent.com/yopaseopor/traffic_signs_preset_JOSM/master/DE.zip
+ https://josm.openstreetmap.de/josmfile?page=Presets/public_bookcase&zip=1

Map paint styles:
- https://raw.githubusercontent.com/yopaseopor/indoormap/master/indoormap-style.mapcss
- https://josm.openstreetmap.de/josmfile?page=Styles/Coloured_Streets&zip=1
- https://www.dropbox.com/s/qo3ai47fpv241jf/Styles_Fixme_and_Notes.zip?raw=1
- https://josm.openstreetmap.de/josmfile?page=Styles/MaxspeedIcons&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Maxspeed&zip=1
- https://github.com/GlassOceanos/indoor-JOSM-style/archive/master.zip
- https://josm.openstreetmap.de/josmfile?page=Styles/ParkingLanes&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/PublicTransport&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Schools&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/PTStops&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Noname&zip=1
Last errors/warnings:
- E: org.openstreetmap.josm.io.OsmApiException: ResponseCode=400, Error Header=<You requested too many nodes (limit is 50000). Either request a smaller area, or use planet.osm>
- E: Fehlerhafte Anfrage - <html>Der OSM-Server »api.openstreetmap.org« meldete eine fehlerhafte Anfrage.<br><br>Das angeforderte Gebiet ist zu groß oder enthält zu viele Daten.<br>Versuchen Sie, ein kleineres Gebiet herunterzuladen oder nutzen Sie einen Datenbankexport.</html>
- E: org.openstreetmap.josm.io.OsmApiException: ResponseCode=400, Error Header=<You requested too many nodes (limit is 50000). Either request a smaller area, or use planet.osm>
- E: Fehlerhafte Anfrage - <html>Der OSM-Server »api.openstreetmap.org« meldete eine fehlerhafte Anfrage.<br><br>Das angeforderte Gebiet ist zu groß oder enthält zu viele Daten.<br>Versuchen Sie, ein kleineres Gebiet herunterzuladen oder nutzen Sie einen Datenbankexport.</html>
- E: org.openstreetmap.josm.io.OsmApiException: ResponseCode=400, Error Header=<You requested too many nodes (limit is 50000). Either request a smaller area, or use planet.osm>
- E: Fehlerhafte Anfrage - <html>Der OSM-Server »api.openstreetmap.org« meldete eine fehlerhafte Anfrage.<br><br>Das angeforderte Gebiet ist zu groß oder enthält zu viele Daten.<br>Versuchen Sie, ein kleineres Gebiet herunterzuladen oder nutzen Sie einen Datenbankexport.</html>
- W: Trying to unset readOnly flag on a non-readOnly dataset 
- E: Handled by bug report queue: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
- W: Achtung - <html>JOSM konnte keine Informationen über die folgenden Erweiterungen finden:<ul><li>ImproveWay</li><li>notesolver</li><li>imagery_offset_db</li><li>HouseNumberTaggingTool</li><li>tageditor</li><li>RoadSigns</li><li>measurement</li><li>continuosDownload</li><li>turnlanes-tagging</li><li>utilsplugin2</li><li>mapathoner</li><li>indoor_sweepline</li><li>OpeningHoursEditor</li><li>undelete</li><li>terracer</li><li>turnrestrictions</li><li>wikipedia</li><li>Tracer2</li><li>contourmerge</li><li>merge-overlap</li></ul>Diese Erweiterungen werden nicht geladen.</html>
- E: Handled by bug report queue: java.lang.NullPointerException


=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException
=== STACK TRACE ===
Thread: AWT-EventQueue-0 (15) of main
java.lang.NullPointerException
  at java.awt.Container.getComponentAt(Unknown Source)
  at org.openstreetmap.josm.plugins.notesolver.NoteSolverPlugin$4.selectedNoteChanged(NoteSolverPlugin.java:131)
  at org.openstreetmap.josm.data.osm.NoteData.lambda$setSelectedNote$0(NoteData.java:109)
  at org.openstreetmap.josm.tools.ListenerList.fireEvent(ListenerList.java:156)
  at org.openstreetmap.josm.data.osm.NoteData.setSelectedNote(NoteData.java:109)
  at org.openstreetmap.josm.gui.dialogs.NotesDialog$CloseAction.actionPerformed(NotesDialog.java:355)
  at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
  at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
  at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
  at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
  at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
  at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
  at java.awt.Component.processMouseEvent(Unknown Source)
  at javax.swing.JComponent.processMouseEvent(Unknown Source)
  at java.awt.Component.processEvent(Unknown Source)
  at java.awt.Container.processEvent(Unknown Source)
  at java.awt.Component.dispatchEventImpl(Unknown Source)
  at java.awt.Container.dispatchEventImpl(Unknown Source)
  at java.awt.Component.dispatchEvent(Unknown Source)
  at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
  at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
  at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
  at java.awt.Container.dispatchEventImpl(Unknown Source)
  at java.awt.Window.dispatchEventImpl(Unknown Source)
  at java.awt.Component.dispatchEvent(Unknown Source)
  at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
  at java.awt.EventQueue.access$500(Unknown Source)
  at java.awt.EventQueue$3.run(Unknown Source)
  at java.awt.EventQueue$3.run(Unknown Source)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
  at java.awt.EventQueue$4.run(Unknown Source)
  at java.awt.EventQueue$4.run(Unknown Source)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
  at java.awt.EventQueue.dispatchEvent(Unknown Source)
  at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
  at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
  at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
  at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
  at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
  at java.awt.EventDispatchThread.run(Unknown Source)
}}}
```

**Comment by kmpoppe** [comment]
Closed by 8609e2a
